apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
   matchLabels:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: autanbr/conversao-temperatura:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: web
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort


